
package br.com.portoseguro.ws.schema;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsultaDadosBCPWS", targetNamespace = "http://www.portoseguro.com.br/bi/integration/ConsultaDadosBCPABCS/V2_0/", wsdlLocation = "file:/C:/desenv/bat/kiprev/kiprev.wsdl")
public class ConsultaDadosBCPWS_Service
    extends Service
{

    private final static URL CONSULTADADOSBCPWS_WSDL_LOCATION;
    private final static WebServiceException CONSULTADADOSBCPWS_EXCEPTION;
    private final static QName CONSULTADADOSBCPWS_QNAME = new QName("http://www.portoseguro.com.br/bi/integration/ConsultaDadosBCPABCS/V2_0/", "ConsultaDadosBCPWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/desenv/bat/kiprev/kiprev.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTADADOSBCPWS_WSDL_LOCATION = url;
        CONSULTADADOSBCPWS_EXCEPTION = e;
    }

    public ConsultaDadosBCPWS_Service() {
        super(__getWsdlLocation(), CONSULTADADOSBCPWS_QNAME);
    }

    public ConsultaDadosBCPWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTADADOSBCPWS_QNAME, features);
    }

    public ConsultaDadosBCPWS_Service(URL wsdlLocation) {
        super(wsdlLocation, CONSULTADADOSBCPWS_QNAME);
    }

    public ConsultaDadosBCPWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTADADOSBCPWS_QNAME, features);
    }

    public ConsultaDadosBCPWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaDadosBCPWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsultaDadosBCPWS
     */
    @WebEndpoint(name = "ConsultaDadosBCPWS")
    public ConsultaDadosBCPWS getConsultaDadosBCPWS() {
        return super.getPort(new QName("http://www.portoseguro.com.br/bi/integration/ConsultaDadosBCPABCS/V2_0/", "ConsultaDadosBCPWS"), ConsultaDadosBCPWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaDadosBCPWS
     */
    @WebEndpoint(name = "ConsultaDadosBCPWS")
    public ConsultaDadosBCPWS getConsultaDadosBCPWS(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portoseguro.com.br/bi/integration/ConsultaDadosBCPABCS/V2_0/", "ConsultaDadosBCPWS"), ConsultaDadosBCPWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTADADOSBCPWS_EXCEPTION!= null) {
            throw CONSULTADADOSBCPWS_EXCEPTION;
        }
        return CONSULTADADOSBCPWS_WSDL_LOCATION;
    }

}
